#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Set, Tuple

CODE_EXTS = {
    ".py": "python",
    ".pyi": "python",
    ".rs": "rust",
    ".go": "go",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".kt": "kotlin",
    ".scala": "scala",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".rb": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".m": "objc",
    ".mm": "objc",
    ".lua": "lua",
    ".sh": "shell",
    ".bash": "shell",
}

BINARY_EXTS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".svg",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".tgz",
    ".xz",
    ".7z",
    ".jar",
    ".war",
    ".class",
    ".o",
    ".so",
    ".a",
    ".dll",
    ".dylib",
    ".exe",
    ".wasm",
    ".mp3",
    ".mp4",
    ".mov",
    ".avi",
    ".bin",
}

GENERATED_MARKERS = [
    "code generated",
    "@generated",
    "do not edit",
    "generated by",
]

ENTRY_POINT_NAMES = {
    "main.rs",
    "main.go",
    "main.py",
    "main.js",
    "main.ts",
    "index.js",
    "index.ts",
    "app.py",
    "app.js",
    "app.ts",
    "server.py",
    "server.js",
    "server.ts",
    "__main__.py",
}

BUILD_FILES = {
    "Cargo.toml",
    "Cargo.lock",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "pyproject.toml",
    "setup.py",
    "requirements.txt",
    "go.mod",
    "go.sum",
    "pom.xml",
    "build.gradle",
    "settings.gradle",
    "Makefile",
    "CMakeLists.txt",
}

COMMENT_PREFIXES = {
    "#",
    "//",
    "/*",
    "*",
    "--",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="repo-processor recon")
    parser.add_argument("target", help="Target path")
    parser.add_argument("output", help="Output JSON path")
    parser.add_argument("--skip-dirs", default="vendor,third_party,node_modules,.git", help="Comma-separated dir names")
    parser.add_argument("--skip-generated", default="true", help="Skip generated files: true|false")
    return parser.parse_args()


def is_binary_file(path: Path) -> bool:
    if path.suffix.lower() in BINARY_EXTS:
        return True
    try:
        with path.open("rb") as f:
            chunk = f.read(1024)
        if b"\x00" in chunk:
            return True
    except Exception:
        return True
    return False


def is_generated_file(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    head = "\n".join(text.splitlines()[:50]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def count_loc(path: Path) -> int:
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    except Exception:
        return 0
    count = 0
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if any(stripped.startswith(prefix) for prefix in COMMENT_PREFIXES):
            continue
        count += 1
    return count


def git_top_level(target: Path) -> str:
    try:
        proc = subprocess.run(
            ["git", "-C", str(target), "rev-parse", "--show-toplevel"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        if proc.returncode == 0:
            return proc.stdout.strip()
    except Exception:
        return ""
    return ""


def main() -> int:
    args = parse_args()
    target = Path(args.target).resolve()
    output = Path(args.output).resolve()

    skip_dirs = {d.strip() for d in args.skip_dirs.split(",") if d.strip()}
    skip_generated = args.skip_generated.lower() == "true"

    if not target.exists() or not target.is_dir():
        raise SystemExit(f"Target path not found or not a directory: {target}")

    top_level = git_top_level(target)
    is_full_repo = top_level == str(target)

    languages_loc: Dict[str, int] = {}
    total_files = 0
    total_loc = 0
    entry_points: Set[str] = set()
    existing_docs: Set[str] = set()
    build_files: Set[str] = set()

    dir_info: Dict[str, Dict[str, object]] = {}
    visited_real: Set[str] = set()

    def ensure_dir_info(rel_path: str) -> None:
        if rel_path not in dir_info:
            dir_info[rel_path] = {
                "path": rel_path,
                "source_files": [],
                "source_loc": 0,
                "subdirs": [],
                "has_generated": False,
            }

    for dirpath, dirnames, filenames in os.walk(target, followlinks=True):
        real = os.path.realpath(dirpath)
        if real in visited_real:
            dirnames[:] = []
            continue
        visited_real.add(real)

        dirnames[:] = [d for d in dirnames if d not in skip_dirs]

        rel_dir = os.path.relpath(dirpath, target)
        if rel_dir == ".":
            rel_dir = ""
        ensure_dir_info(rel_dir)

        for d in dirnames:
            child_rel = os.path.join(rel_dir, d) if rel_dir else d
            ensure_dir_info(child_rel)
            dir_info[rel_dir]["subdirs"].append(d)

        for filename in filenames:
            total_files += 1
            file_path = Path(dirpath) / filename
            if file_path.is_symlink():
                continue
            if is_binary_file(file_path):
                continue

            rel_path = os.path.relpath(file_path, target)

            if filename in ENTRY_POINT_NAMES:
                entry_points.add(rel_path)

            if filename in BUILD_FILES and rel_dir == "":
                build_files.add(rel_path)

            if filename.lower().endswith(".md"):
                if rel_dir == "" or rel_dir.startswith("docs"):
                    existing_docs.add(rel_path)

            ext = file_path.suffix.lower()
            if ext not in CODE_EXTS:
                continue

            generated = is_generated_file(file_path)
            if generated:
                dir_info[rel_dir]["has_generated"] = True
                if skip_generated:
                    continue

            loc = count_loc(file_path)
            total_loc += loc
            lang = CODE_EXTS.get(ext, "other")
            languages_loc[lang] = languages_loc.get(lang, 0) + loc

            dir_info[rel_dir]["source_files"].append(filename)
            dir_info[rel_dir]["source_loc"] += loc

    total_loc_nonzero = total_loc if total_loc > 0 else 1
    languages = {
        lang: int(round(loc * 100 / total_loc_nonzero))
        for lang, loc in sorted(languages_loc.items(), key=lambda kv: kv[1], reverse=True)
    }

    directory_tree = []
    for rel_path, info in sorted(dir_info.items(), key=lambda kv: kv[0]):
        directory_tree.append(info)

    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "target_path": str(target),
        "is_full_repo": is_full_repo,
        "languages": languages,
        "total_files": total_files,
        "total_loc": total_loc,
        "entry_points": sorted(entry_points),
        "build_files": sorted(build_files),
        "existing_docs": sorted(existing_docs),
        "directory_tree": directory_tree,
    }
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
